### ISSUE TITLE
App doesn’t work

### ISSUE THREAD

**Issue by zisop16** [shug-op/eriv#1]
I tried to upload my files to ur website but your mom keeps sucking my penis. Help?

**Comment by zisop16** [comment]
you’re*

**Comment by zisop16** [comment]
u’re*

**Comment by starskyreverie** [comment]
hey, zisop. thanks for the issue. to answer your question, yes, i did have sex with your mother last night. and yes - it was enjoyable. 

see you soon, zisop.
-shug
